In [ ]:
import numpy as np
#1차원 배열만들기
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar

In [ ]:
ar=np.arange(10)
ar

In [ ]:
type(ar)

In [ ]:
# 1차원 리스트를 reshape해서 2차원 배열을 생성
arr = np.array([5] * 15).reshape((3, 5))
print(arr)
# [[5 5 5 5 5]
#  [5 5 5 5 5]
#  [5 5 5 5 5]]

In [ ]:
# 1차원 range를 reshape해서 2차원 배열 생성
arr = np.arange(25).reshape((5, 5))
print(arr)
# [[ 0  1  2  3  4]
#  [ 5  6  7  8  9]
#  [10 11 12 13 14]
#  [15 16 17 18 19]
#  [20 21 22 23 24]]

In [ ]:
row, column = 2, 3
arr_2d = np.array([[None] * column for i in range(row)])
arr_2d
# [[None, None, None], [None, None, None]]

In [ ]:
#벡터화 연산
#각 요소를 2배하는 경우 기존의 for문사용
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
answer = []
for di in data:
    answer.append(2 * di)  #각 
    
answer

In [ ]:
#벡터화 연산 사용
x = np.array(data)
2 * x

In [ ]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
a  - b

In [ ]:
(a == 2) & (b > 10)

In [ ]:
#2차원 배열만들기
c = np.array([[0, 1, 2], [3, 4, 5]])  # 2 x 3 array
# c =np.arange(6).reshape((2, 3))
c

In [ ]:
# 행의 갯수
len(c)

In [ ]:
# 열의 갯수
len(c[0])

In [ ]:
#3차원 배열
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])   # 2 x 3 x 4 array

In [ ]:
#배열의 차원과 크기
# c = np.array([[0, 1, 2], [3, 4, 5]])
print(c.ndim)
print(c.shape)

In [ ]:
print(d.ndim)
print(d.shape)

In [ ]:
#배열 인덱싱
#일차원배열= 리스트와 동일
a = np.array([0, 1, 2, 3, 4])
a[2]
a[-1]

In [ ]:
#다차원배열
a = np.array([[0, 1, 2], [3, 4, 5]])
a[0, 1]  # 첫번째 행의 두번째 열
# a[-1, -1]  # 마지막 행의 마지막 열

In [ ]:
#팬시 인덱싱(fancy indexing)―배열인덱싱
#불리언 배열방식
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
               False, True, False, True, False])
a[idx]

In [ ]:
a % 2 == 0

In [ ]:
#조건문연산식을 사용한 인덱싱
a[a%2==0]  

In [ ]:
#정수 배열 방식
            # 0    1   2   3   4   5  6   7   8
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])  #원소객체 하나의 인덱스
a[idx]

In [ ]:
#배열 슬라이싱

In [ ]:
#인덱싱+슬라이싱
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[[0,1], :]  #a[[0,1]]=> 0,1번째 리스트원소를 인덱싱 , : 모든열

In [ ]:
#연습문제
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])
m
#이 행렬에서 값 7 을 인덱싱한다.
# 이 행렬에서 값 14 을 인덱싱한다.
# 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
# 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
# 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

In [ ]:
m[1,2]

In [ ]:
m[-1,-1]

In [ ]:
m[1,1:3]

In [ ]:
m[1:,2]

In [ ]:
m[:2,3:5]

In [ ]:
m[[0,1], 3:5]

In [ ]:
m[[1], 1:3]